export type Status =
  | "backlog"
  | "ready"
  | "implementing"
  | "verify"
  | "blocked"
  | "done";

export type Risk = "低" | "中" | "高";
export type Basis = "已有證據" | "未來規劃" | "人工關卡";

export type Architecture =
  | "介面"
  | "前端"
  | "資料"
  | "後端"
  | "AI"
  | "自動化"
  | "治理安全"
  | "測試發布";

export type Task = {
  id: string;
  title: string;
  summary: string;
  status: Status;
  risk: Risk;
  owner: string;
  epic: string;
  story: string;
  architecture: Architecture;
  basis: Basis;
  start: string;
  due: string;
  dependencies: string[];
  gate?: string;
  evidence: string[];
  acceptance: string[];
};

export const architectureOrder: Architecture[] = [
  "介面",
  "前端",
  "資料",
  "後端",
  "AI",
  "自動化",
  "治理安全",
  "測試發布",
];

export type ArchitectureBlock = {
  name: Architecture;
  code: string;
  layer: "使用體驗層" | "資料智慧層" | "信任交付層";
  purpose: string;
  includes: string[];
  next: string;
  dependsOn: Architecture[];
};

export const architectureBlocks: ArchitectureBlock[] = [
  {
    name: "介面",
    code: "UI",
    layer: "使用體驗層",
    purpose: "決定使用者看見什麼、怎麼理解資訊，以及在手機與電腦上怎麼操作。",
    includes: ["資訊層級", "公司黃金頁", "工作台", "圖表與互動"],
    next: "依 26 家獨立審查結果，修正公司特有內容與資訊密度。",
    dependsOn: ["前端", "資料"],
  },
  {
    name: "前端",
    code: "FE",
    layer: "使用體驗層",
    purpose: "把資料安全地組成可搜尋、可操作、跨裝置一致的實際頁面。",
    includes: ["共用頁面元件", "搜尋與路由", "資料顯示轉接", "響應式行為"],
    next: "完成第二條價值鏈的 5 家公司頁編輯波次。",
    dependsOn: ["後端", "資料", "介面"],
  },
  {
    name: "資料",
    code: "DATA",
    layer: "資料智慧層",
    purpose: "管理公司、產品、價值鏈關係、來源證據與計算方法，確保每個結論有依據。",
    includes: ["公司本體", "來源證據", "關係與角色", "市場資料與方法"],
    next: "完成 26 家審查回饋與調整後報酬方法論確認。",
    dependsOn: ["治理安全"],
  },
  {
    name: "後端",
    code: "BE",
    layer: "資料智慧層",
    purpose: "負責資料庫、批次寫入、讀回、回復與前台需要的安全資料格式。",
    includes: ["Supabase／PostgreSQL", "批次寫入", "read model", "回復與版本"],
    next: "人工安全控制完成後，啟動第二價值鏈 100 家身分批次。",
    dependsOn: ["資料", "治理安全"],
  },
  {
    name: "AI",
    code: "AI",
    layer: "資料智慧層",
    purpose: "協助大量研究、整理來源與提出候選關係，但不能自己把候選升級成事實。",
    includes: ["研究 Agent", "來源整理", "候選關係", "缺口與衝突提示"],
    next: "依新價值鏈範圍，完成 20 家深度研究並交由人工審查。",
    dependsOn: ["資料", "治理安全"],
  },
  {
    name: "自動化",
    code: "AUTO",
    layer: "資料智慧層",
    purpose: "讓研究、檢查、排程、過期提醒與失敗通知可以重複執行並留下紀錄。",
    includes: ["Harness／Canary", "批次流程", "排程", "失敗與過期告警"],
    next: "決定正式排程環境、通知對象與值班責任。",
    dependsOn: ["後端", "治理安全"],
  },
  {
    name: "治理安全",
    code: "GOV",
    layer: "信任交付層",
    purpose: "管理候選、審查、驗證、發布的界線，也保護權限、密碼、個資與人工決策。",
    includes: ["資料狀態關卡", "獨立 Reviewer", "權限與機密", "發布核准"],
    next: "先完成 26 家獨立審查與資料庫人工安全控制。",
    dependsOn: [],
  },
  {
    name: "測試發布",
    code: "QA",
    layer: "信任交付層",
    purpose: "確認功能、資料、安全與各裝置都通過，最後才決定是否預發布或正式上線。",
    includes: ["回歸測試", "三尺寸驗收", "圖譜複審", "上線與回復"],
    next: "完成 A14 圖譜複審；所有關卡通過前不進入公開發布。",
    dependsOn: ["介面", "前端", "資料", "後端", "治理安全"],
  },
];

export type PlanPhase = {
  id: "P0" | "P1" | "P2" | "P3";
  title: string;
  period: string;
  outcome: string;
  taskIds: string[];
  exitCriteria: string[];
  basis: Basis;
};

export const planPhases: PlanPhase[] = [
  {
    id: "P0",
    title: "鎖定可信基線",
    period: "2026/07/21—07/27",
    outcome: "保存 26 家候選公司頁、主線測試與本機工作台，清楚標示尚未發布。",
    taskIds: [
      "TASK-097",
      "TASK-098",
      "TASK-099",
      "TASK-100",
      "TASK-101",
      "TASK-102",
      "TASK-103",
      "TASK-104",
    ],
    exitCriteria: [
      "候選公司頁成果可由任務文件與 Git 核對",
      "主線測試通過",
      "production、verified 與 public release 維持關閉",
    ],
    basis: "已有證據",
  },
  {
    id: "P1",
    title: "關閉人工與方法關卡",
    period: "2026/07/27—08/14",
    outcome: "完成 26 家獨立審查、資料庫安全控制、圖譜複審與計算方法決策。",
    taskIds: [
      "TASK-105",
      "TASK-106",
      "TASK-107",
      "TASK-108",
      "TASK-109",
      "TASK-110",
    ],
    exitCriteria: [
      "26 家都有獨立 reviewer decision",
      "資料庫人工安全紀錄完成",
      "A14 與調整後報酬方法留下明確 verdict",
      "正式排程與告警責任已決定",
    ],
    basis: "人工關卡",
  },
  {
    id: "P2",
    title: "演練第二條價值鏈",
    period: "2026/08/10—09/14",
    outcome: "用同一套治理方式完成 100 家建檔、20 家研究、5 家頁面與三尺寸驗收。",
    taskIds: [
      "TASK-111",
      "TASK-112",
      "TASK-113",
      "TASK-114",
      "TASK-115",
    ],
    exitCriteria: [
      "價值鏈範圍與停止條件鎖定",
      "100 家公司本體可追溯",
      "20 家研究證據可送審",
      "5 家頁面通過搜尋、安全與三尺寸 QA",
    ],
    basis: "未來規劃",
  },
  {
    id: "P3",
    title: "做發布 Go／No-Go 決策",
    period: "2026/09/15—09/25",
    outcome: "彙整資料、產品、安全與測試證據，決定是否進預發布與正式上線。",
    taskIds: ["TASK-116", "TASK-117"],
    exitCriteria: [
      "所有必要人工與機械關卡都有證據",
      "候選、verified、published 狀態不混用",
      "上線、監控與回復方案完成",
      "取得新的明確發布授權",
    ],
    basis: "人工關卡",
  },
];

export const planMilestones = [
  {
    id: "M0",
    date: "2026/07/27",
    title: "候選基線與工作台鎖定",
    basis: "已有證據" as Basis,
    taskIds: ["TASK-103", "TASK-104"],
  },
  {
    id: "M1",
    date: "2026/08/14",
    title: "第一輪人工關卡完成",
    basis: "未來規劃" as Basis,
    taskIds: ["TASK-105", "TASK-107", "TASK-108", "TASK-109", "TASK-110"],
  },
  {
    id: "M2",
    date: "2026/09/14",
    title: "第二價值鏈 5 家頁面完成驗收",
    basis: "未來規劃" as Basis,
    taskIds: ["TASK-112", "TASK-113", "TASK-114", "TASK-115"],
  },
  {
    id: "M3",
    date: "2026/09/25",
    title: "發布 Go／No-Go",
    basis: "人工關卡" as Basis,
    taskIds: ["TASK-116", "TASK-117"],
  },
];

export const criticalPath = [
  "TASK-105",
  "TASK-111",
  "TASK-112",
  "TASK-113",
  "TASK-114",
  "TASK-115",
  "TASK-116",
  "TASK-117",
];

export const columns: { id: Status; label: string; hint: string }[] = [
  { id: "backlog", label: "待辦", hint: "尚未承諾" },
  { id: "ready", label: "就緒", hint: "可立即開始" },
  { id: "implementing", label: "進行中", hint: "WIP 上限 3" },
  { id: "verify", label: "驗證中", hint: "等待證據" },
  { id: "blocked", label: "受阻", hint: "需要排除" },
  { id: "done", label: "完成", hint: "已通過任務關卡" },
];

export const seedTasks: Task[] = [
  {
    id: "TASK-097",
    title: "20 家半導體黃金頁標準化",
    summary: "20 家公司的資料都能套用同一套頁面，並在電腦、平板與手機正常閱讀。",
    status: "done",
    risk: "高",
    owner: "產品＋資料",
    epic: "公司黃金頁產品化",
    story: "使用者能以一致結構理解公司的價值鏈位置",
    architecture: "介面",
    basis: "已有證據",
    start: "2026-07-21",
    due: "2026-07-25",
    dependencies: [],
    evidence: ["tasks/TASK-097.md", "20 / 20 三尺寸自動 UI 驗收", "golden_review_ready_release_blocked"],
    acceptance: ["20 家共用同一 renderer", "候選資料不升級 verified", "保留逐家公司獨立審查"],
  },
  {
    id: "TASK-098",
    title: "10,000 家公司頁擴張地基",
    summary: "把大量公司工作拆成 100、20、5、1 家四種批次，每一步都能檢查與回復。",
    status: "done",
    risk: "高",
    owner: "系統架構",
    epic: "規模化資料與公司頁",
    story: "團隊能以可回復批次擴張公司資料",
    architecture: "後端",
    basis: "已有證據",
    start: "2026-07-24",
    due: "2026-07-26",
    dependencies: ["TASK-097"],
    evidence: ["tasks/TASK-098.md", "scale canary 20 / 20", "foundation_complete_release_blocked"],
    acceptance: ["批次可重跑與 rollback", "單一中央 writer", "production gate 維持關閉"],
  },
  {
    id: "TASK-099",
    title: "單家公司完整 Pilot",
    summary: "用信驊完整走過研究、資料寫入、頁面呈現、測試與送審流程。",
    status: "done",
    risk: "高",
    owner: "資料研究",
    epic: "規模化資料與公司頁",
    story: "團隊能證明單家公司流程可完整重現",
    architecture: "資料",
    basis: "已有證據",
    start: "2026-07-25",
    due: "2026-07-26",
    dependencies: ["TASK-098"],
    evidence: ["tasks/TASK-099.md", "15 / 15 slots", "1440 / 1024 / 390 passed"],
    acceptance: ["dev write 可逆", "review packet 完整", "狀態不超過 release blocked"],
  },
  {
    id: "TASK-100",
    title: "五家公司黃金頁 Pilot",
    summary: "把單家公司流程擴大到五家公司，確認批次處理仍能穩定完成。",
    status: "done",
    risk: "高",
    owner: "資料研究",
    epic: "規模化資料與公司頁",
    story: "團隊能以五家公司波次穩定交付候選頁",
    architecture: "AI",
    basis: "已有證據",
    start: "2026-07-25",
    due: "2026-07-26",
    dependencies: ["TASK-099"],
    evidence: ["tasks/TASK-100.md", "five-company pilot canary 14 / 14"],
    acceptance: ["五家公司皆可由 DB read model 重建", "研究與 reviewer 角色分離"],
  },
  {
    id: "TASK-101",
    title: "五家公司通用搜尋整合",
    summary: "輸入公司代碼、名稱、產品或應用，就能直接找到新增的公司頁。",
    status: "done",
    risk: "中",
    owner: "前端",
    epic: "公司黃金頁產品化",
    story: "使用者能從原有搜尋找到新增公司",
    architecture: "前端",
    basis: "已有證據",
    start: "2026-07-26",
    due: "2026-07-26",
    dependencies: ["TASK-100"],
    evidence: ["tasks/TASK-101.md", "搜尋 canary 9 / 9"],
    acceptance: ["不新增平行 renderer", "既有 2330 搜尋不退化"],
  },
  {
    id: "TASK-102",
    title: "市場圖表固定與滑桿互動",
    summary: "圖表可以固定選取日期、拖曳查看，也能用鍵盤操作並看懂價格單位。",
    status: "done",
    risk: "中",
    owner: "介面",
    epic: "公司黃金頁產品化",
    story: "使用者能精準查看每日收盤價",
    architecture: "介面",
    basis: "已有證據",
    start: "2026-07-26",
    due: "2026-07-26",
    dependencies: ["TASK-097"],
    evidence: ["tasks/TASK-102.md", "三尺寸圖表互動 QA"],
    acceptance: ["pointer、touch、keyboard 共用狀態", "手機無溢位"],
  },
  {
    id: "TASK-103",
    title: "候選黃金頁併入本機與遠端 main",
    summary: "已把候選公司頁安全合併到主要版本並完成全面測試，但還沒有公開發布。",
    status: "done",
    risk: "高",
    owner: "發布治理",
    epic: "品質與發布治理",
    story: "團隊能以一致主線保存已驗證候選成果",
    architecture: "測試發布",
    basis: "已有證據",
    start: "2026-07-26",
    due: "2026-07-26",
    dependencies: ["TASK-100", "TASK-101", "TASK-102"],
    evidence: ["tasks/TASK-103.md", "main / origin-main 89f34e8f", "主 Harness 391 / 391"],
    acceptance: ["本機與遠端 main SHA 一致", "gh-pages 與 production 未發布"],
  },
  {
    id: "TASK-104",
    title: "專案工作台、架構分類與甘特圖",
    summary: "把目前狀態、工作分類、依賴與排程放入同一個本機控制台。",
    status: "done",
    risk: "低",
    owner: "Codex",
    epic: "專案管理與決策",
    story: "產品負責人能從狀態、架構與時間三個角度掌握專案",
    architecture: "介面",
    basis: "已有證據",
    start: "2026-07-26",
    due: "2026-07-27",
    dependencies: [],
    evidence: ["project-workbench/app/project-plan.ts", "看板／藍圖／甘特圖"],
    acceptance: ["工作有明確架構分類", "甘特圖顯示日期與依賴", "本機狀態可保存"],
  },
  {
    id: "TASK-105",
    title: "26 家候選黃金頁獨立審查",
    summary: "由沒有參與研究與製作的人，逐家公司決定通過或退回補資料。",
    status: "ready",
    risk: "高",
    owner: "獨立 Reviewer",
    epic: "公司黃金頁產品化",
    story: "候選公司頁能取得獨立且可追溯的審查結果",
    architecture: "治理安全",
    basis: "人工關卡",
    start: "2026-07-27",
    due: "2026-08-07",
    dependencies: ["TASK-103"],
    evidence: ["20 家 review packets", "1 家 pilot packet", "5 家 pilot packets"],
    acceptance: ["26 家逐一留 decision", "研究者不得自審", "未通過者維持 release blocked"],
  },
  {
    id: "TASK-106",
    title: "審查退回修正波次",
    summary: "依審查意見補齊來源、修正文案，並把每家公司的特有內容做完整。",
    status: "backlog",
    risk: "中",
    owner: "資料＋前端",
    epic: "公司黃金頁產品化",
    story: "被退回的公司能在不降低證據門檻下完成修正",
    architecture: "介面",
    basis: "未來規劃",
    start: "2026-08-10",
    due: "2026-08-14",
    dependencies: ["TASK-105"],
    evidence: ["待由 TASK-105 產生退回類型矩陣"],
    acceptance: ["每項修正對應 reviewer finding", "共用 renderer 無 P0 / P1 regression"],
  },
  {
    id: "TASK-107",
    title: "資料庫人工安全控制",
    summary: "限制只有可信任的設備能連資料庫，必要時更換密碼並留下不含機密的紀錄。",
    status: "blocked",
    risk: "高",
    owner: "產品負責人",
    epic: "品質與發布治理",
    story: "候選資料平台能關閉剩餘人工安全缺口",
    architecture: "治理安全",
    basis: "人工關卡",
    start: "2026-07-27",
    due: "2026-07-31",
    dependencies: [],
    gate: "需要可信任固定 IP／CIDR 與人工操作 Supabase",
    evidence: ["docs/MANUAL_DB_CONTROLS_NEXT_ACTIONS.md", "缺 2 份 security receipts"],
    acceptance: ["不使用 0.0.0.0/0", "密碼不進 Git 或前台", "security canary 通過"],
  },
  {
    id: "TASK-108",
    title: "A14 圖譜凍結包重新複審",
    summary: "重新確認目前主要版本的圖譜證據；沒有審查通過就不開放。",
    status: "blocked",
    risk: "高",
    owner: "獨立 Reviewer",
    epic: "品質與發布治理",
    story: "圖譜與報告只有在證據重新確認後才能進入下一關",
    architecture: "測試發布",
    basis: "人工關卡",
    start: "2026-07-28",
    due: "2026-08-03",
    dependencies: ["TASK-103"],
    gate: "目前狀態 PENDING_A14_REREVIEW",
    evidence: ["TASK-103 pre-push evidence", "16 / 16 mutation canaries", "7 / 7 upstream validators"],
    acceptance: ["獨立複審留下 verdict", "未核准前不開放 graph/report"],
  },
  {
    id: "TASK-109",
    title: "調整後報酬方法論審查",
    summary: "確認股利、除權息等事件怎麼影響報酬計算，避免把未確認數字當成事實。",
    status: "blocked",
    risk: "高",
    owner: "方法論 Reviewer",
    epic: "資料可信度與計算",
    story: "使用者看到的報酬數字有可解釋且可重算的方法",
    architecture: "資料",
    basis: "人工關卡",
    start: "2026-08-03",
    due: "2026-08-07",
    dependencies: [],
    gate: "需要人工方法論核准",
    evidence: ["market-adjustment-harness", "candidate_adjusted_return_model_ready_claim_blocked"],
    acceptance: ["來源與重算 canary 通過", "核准前不宣稱 verified adjusted return"],
  },
  {
    id: "TASK-110",
    title: "正式排程與告警目的地決策",
    summary: "決定資料過期或工作失敗時，由哪個系統通知、通知誰、誰負責處理。",
    status: "backlog",
    risk: "中",
    owner: "平台營運",
    epic: "品質與發布治理",
    story: "平台失敗或資料過期時能找到負責人",
    architecture: "自動化",
    basis: "未來規劃",
    start: "2026-08-03",
    due: "2026-08-07",
    dependencies: ["TASK-107"],
    evidence: ["freshness-alert-harness", "local_monitor_ready_production_scheduler_blocked"],
    acceptance: ["明確 scheduler 與 alert destination", "失敗路徑可測", "未核准前維持本機"],
  },
  {
    id: "TASK-111",
    title: "下一條價值鏈選擇與範圍鎖定",
    summary: "先用 26 家公司的審查結果修正做法，再選下一個要擴張的產業鏈。",
    status: "blocked",
    risk: "中",
    owner: "產品負責人",
    epic: "下一條價值鏈擴張",
    story: "團隊能在擴量前鎖定可證明的產品與研究範圍",
    architecture: "治理安全",
    basis: "未來規劃",
    start: "2026-08-10",
    due: "2026-08-12",
    dependencies: ["TASK-105"],
    gate: "需先取得 26 家獨立審查回饋",
    evidence: ["docs/COMPANY_PAGE_SCALE_OPERATING_MODEL_V1.0.md"],
    acceptance: ["確認價值鏈與停止條件", "SOP 以新版本保存", "不覆寫歷史契約"],
  },
  {
    id: "TASK-112",
    title: "第二價值鏈 100 家身分批次",
    summary: "先確認 100 家公司是誰、官方來源在哪裡，不急著推論上下游關係。",
    status: "backlog",
    risk: "中",
    owner: "資料工程",
    epic: "下一條價值鏈擴張",
    story: "團隊能建立可供深度研究的正確公司母體",
    architecture: "後端",
    basis: "未來規劃",
    start: "2026-08-13",
    due: "2026-08-21",
    dependencies: ["TASK-111", "TASK-107"],
    evidence: ["待建立 batch manifest 與 identity receipts"],
    acceptance: ["100 家唯一 companyEntityKey", "來源可追溯", "無 production write"],
  },
  {
    id: "TASK-113",
    title: "第二價值鏈 20 家深度研究",
    summary: "深入研究 20 家公司的產品、上下游、地理、風險與替代關係，並附上來源。",
    status: "backlog",
    risk: "高",
    owner: "研究 Agent＋人工",
    epic: "下一條價值鏈擴張",
    story: "分析者能從公司本體理解真實市場角色",
    architecture: "AI",
    basis: "未來規劃",
    start: "2026-08-24",
    due: "2026-09-04",
    dependencies: ["TASK-112"],
    evidence: ["待建立 20 家 research operation paths"],
    acceptance: ["每個具名關係有來源、日期與範圍", "不足者誠實標 blocked", "dev write 可回復"],
  },
  {
    id: "TASK-114",
    title: "第二價值鏈 5 家前台編輯波次",
    summary: "先完成一家公司作為樣板，確認方向後再製作同一批的另外四家。",
    status: "backlog",
    risk: "中",
    owner: "前端＋內容",
    epic: "下一條價值鏈擴張",
    story: "使用者能以相同資訊架構閱讀不同價值鏈公司",
    architecture: "前端",
    basis: "未來規劃",
    start: "2026-09-07",
    due: "2026-09-11",
    dependencies: ["TASK-113"],
    evidence: ["待建立 frontend-safe payload 與 visual canary"],
    acceptance: ["不複製其他公司事實", "先驗 1101 與 2330", "一般前台不含治理內部欄位"],
  },
  {
    id: "TASK-115",
    title: "第二價值鏈三尺寸與回歸驗收",
    summary: "確認五家公司在電腦、平板、手機都能正常搜尋、閱讀與操作。",
    status: "backlog",
    risk: "中",
    owner: "QA",
    epic: "下一條價值鏈擴張",
    story: "第二價值鏈公司頁能在各裝置可靠使用",
    architecture: "測試發布",
    basis: "未來規劃",
    start: "2026-09-10",
    due: "2026-09-14",
    dependencies: ["TASK-114"],
    evidence: ["待產生 viewport QA 與 canary reports"],
    acceptance: ["零水平溢位", "零執行期錯誤", "敏感欄位掃描通過"],
  },
  {
    id: "TASK-116",
    title: "圖譜／報告 release gate 決策",
    summary: "把圖譜複審、人工測試、資料可信度與安全結果放在一起，決定能否進入預發布。",
    status: "blocked",
    risk: "高",
    owner: "產品負責人",
    epic: "品質與發布治理",
    story: "發布者能根據完整證據做可回復的 go／no-go",
    architecture: "治理安全",
    basis: "人工關卡",
    start: "2026-09-15",
    due: "2026-09-18",
    dependencies: ["TASK-105", "TASK-107", "TASK-108", "TASK-109", "TASK-110", "TASK-115"],
    gate: "所有人工與機械關卡完成前維持 blocked",
    evidence: ["graph-report-release-gate-harness", "待完成 release checklist"],
    acceptance: ["候選、verified、published 明確分層", "沒有任意 JSON 進公開 snapshot"],
  },
  {
    id: "TASK-117",
    title: "Production／公開發布獨立決策",
    summary: "所有關卡都通過後，再另外決定是否正式上線、開放 API 與搜尋引擎收錄。",
    status: "blocked",
    risk: "高",
    owner: "產品負責人",
    epic: "品質與發布治理",
    story: "產品負責人保留正式上線的最終控制權",
    architecture: "測試發布",
    basis: "人工關卡",
    start: "2026-09-21",
    due: "2026-09-25",
    dependencies: ["TASK-116"],
    gate: "尚未授權 production write、public release 或 verified promotion",
    evidence: ["待 TASK-116 產生 go／no-go evidence"],
    acceptance: ["需新一輪明確人工授權", "回復方案與監控就緒", "不得以 main merge 取代發布核准"],
  },
];

export const timeline = {
  start: "2026-07-21",
  end: "2026-09-25",
  today: "2026-07-26",
};
